SFL_DROP(net_unreachable,0)
SFL_DROP(host_unreachable,1)
SFL_DROP(protocol_unreachable,2)
SFL_DROP(port_unreachable,3)
SFL_DROP(frag_needed,4)
SFL_DROP(src_route_failed,5)
SFL_DROP(dst_net_unknown,6) /* ipv4_lpm_miss, ipv6_lpm_miss */
SFL_DROP(dst_host_unknown,7)
SFL_DROP(src_host_isolated,8)
SFL_DROP(dst_net_prohibited,9) /* reject_route */
SFL_DROP(dst_host_prohibited,10)
SFL_DROP(dst_net_tos_unreachable,11)
SFL_DROP(dst_host_tos_unreacheable,12)
SFL_DROP(comm_admin_prohibited,13)
SFL_DROP(host_precedence_violation,14)
SFL_DROP(precedence_cutoff,15)
SFL_DROP(unknown,256)
SFL_DROP(ttl_exceeded,257) /* ttl_value_is_too_small */
SFL_DROP(acl,258) /* ingress_flow_action_drop, egress_flow_action_drop, group acl_drops */
SFL_DROP(no_buffer_space,259) /* tail_drop */
SFL_DROP(red,260)
SFL_DROP(traffic_shaping,261)
SFL_DROP(pkt_too_big,262) /* mtu_value_is_too_small */
SFL_DROP(src_mac_is_multicast,263)
SFL_DROP(vlan_tag_mismatch,264)
SFL_DROP(ingress_vlan_filter,265)
SFL_DROP(ingress_spanning_tree_filter,266)
SFL_DROP(port_list_is_empty,267)
SFL_DROP(port_loopback_filter,268)
SFL_DROP(blackhole_route,269)
SFL_DROP(non_ip,270)
SFL_DROP(uc_dip_over_mc_dmac,271)
SFL_DROP(dip_is_loopback_address,272)
SFL_DROP(sip_is_mc,273)
SFL_DROP(sip_is_loopback_address,274)
SFL_DROP(ip_header_corrupted,275)
SFL_DROP(ipv4_sip_is_limited_bc,276)
SFL_DROP(ipv6_mc_dip_reserved_scope,277)
SFL_DROP(ipv6_mc_dip_interface_local_scope,278)
SFL_DROP(unresolved_neigh,279)
SFL_DROP(mc_reverse_path_forwarding,280)
SFL_DROP(non_routable_packet,281)
SFL_DROP(decap_error,282)
SFL_DROP(overlay_smac_is_mc,283)
SFL_DROP(unknown_l2,284) /* group l2_drops */
SFL_DROP(unknown_l3,285) /* group l3_drops */
SFL_DROP(unknown_l3_exception,286) /* group l3_exceptions */
SFL_DROP(unknown_buffer,287) /* group buffer_drops */
SFL_DROP(unknown_tunnel,288) /* group tunnel_drops */
SFL_DROP(unknown_l4,289)
SFL_DROP(sip_is_unspecified,290)
SFL_DROP(mlag_port_isolation,291)
SFL_DROP(blackhole_arp_neigh,292)
SFL_DROP(src_mac_is_dmac,293)
SFL_DROP(dmac_is_reserved,294)
SFL_DROP(sip_is_class_e,295)
SFL_DROP(mc_dmac_mismatch,296)
SFL_DROP(sip_is_dip,297)
SFL_DROP(dip_is_local_network,298)
SFL_DROP(dip_is_link_local,299)
SFL_DROP(overlay_smac_is_dmac,300)
SFL_DROP(egress_vlan_filter,301)
SFL_DROP(uc_reverse_path_forwarding,302)
SFL_DROP(split_horizon,303)
SFL_DROP(locked_port,304)
SFL_DROP(dmac_filter,305)
SFL_DROP(blackhole_nexthop,306)
SFL_DROP(vxlan_parsing,307)
SFL_DROP(llc_snap_parsing,308)
SFL_DROP(vlan_parsing,309)
SFL_DROP(pppoe_ppp_parsing,310)
SFL_DROP(mpls_parsing,311)
SFL_DROP(arp_parsing,312)
SFL_DROP(ip_1_parsing,313)
SFL_DROP(ip_n_parsing,314)
SFL_DROP(gre_parsing,315)
SFL_DROP(udp_parsing,316)
SFL_DROP(tcp_parsing,317)
SFL_DROP(ipsec_parsing,318)
SFL_DROP(sctp_parsing,319)
SFL_DROP(dccp_parsing,320)
SFL_DROP(gtp_parsing,321)
SFL_DROP(esp_parsing,322)
SFL_DROP(unknown_parsing,323) /* group parser_error_drops */
SFL_DROP(pkt_too_small,324)
SFL_DROP(unhandled_proto,325)
SFL_DROP(ipv6disabled,326)
SFL_DROP(invalid_proto,327)
SFL_DROP(ip_noproto,328)
SFL_DROP(skb_csum,329)
SFL_DROP(skb_ucopy_fault,330)
SFL_DROP(dev_ready,331)
SFL_DROP(dev_hdr,33)
SFL_DROP(dup_frag,333)
SFL_DROP(skb_gso_seg,334)
SFL_DROP(reverse_path_forwarding,335) /* ip_rpfilter */
SFL_DROP(icmp_parsing,336) /* icmp_csum */
SFL_DROP(tcp_md5notfound,337)
SFL_DROP(tcp_md5unexpected,338)
SFL_DROP(tcp_md5failure,339)
SFL_DROP(tcp_flags,340)
SFL_DROP(tcp_zerowindow,341)
SFL_DROP(tcp_old_data,342)
SFL_DROP(tcp_overwindow,343)
SFL_DROP(tcp_ofomerge,344)
SFL_DROP(tcp_rfc7323_paws,345)
SFL_DROP(tcp_invalid_sequence,346)
SFL_DROP(tcp_reset,347)
SFL_DROP(tcp_invalid_syn,348)
SFL_DROP(tcp_close,349)
SFL_DROP(tcp_fastopen,350)
SFL_DROP(tcp_old_ack,351)
SFL_DROP(tcp_too_old_ack,352)
SFL_DROP(tcp_ack_unsent_data,353)
SFL_DROP(tcp_ofo_queue_prune,354)
SFL_DROP(tcp_ofo_drop,355)
SFL_DROP(tcp_minttl,356)
SFL_DROP(ipv6_bad_exthdr,357)
SFL_DROP(ipv6_ndisc_frag,358)
SFL_DROP(ipv6_ndisc_hop_limit,359)
SFL_DROP(ipv6_ndisc_bad_code,360)
SFL_DROP(ipv6_ndisc_bad_options,361)
SFL_DROP(ipv6_ndisc_ns_otherhost,362)
SFL_DROP(tap_filter,363)
SFL_DROP(tap_txfilter,364)
SFL_DROP(tc_ingress,365)
SFL_DROP(tc_egress,36)
SFL_DROP(xdp,367)
SFL_DROP(cpu_backlog,368)
SFL_DROP(bpf_cgroup_egress,369)
SFL_DROP(xfrm_policy,370)
SFL_DROP(socket_filter,371)
